<a href="https://colab.research.google.com/github/MmayankSharma987/Python-for-Data-Science/blob/main/Python_Libraries_for_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1) Numpy- Numerical Python

In [ ]:
#NumPy- The first step to use NumPy is to tell Python to import NumPy
import numpy as np

##1.1) NumPy Arrays- It store values of same data type. np array can compute even large data sets unlike list functions in python. we can create np array by converting list into array.

In [ ]:
#list of different car brands, data type (string) is same
car_brands = ['Mercedies','BMW','Audi','Feerai','Tesla']
car_brands

['Mercedies', 'BMW', 'Audi', 'Feerai', 'Tesla']

In [ ]:
#list of cylindrs used in cars or numerical elements, data type (integer) is same.
num_cylinders = [5,4,6,7,3]
num_cylinders

[5, 4, 6, 7, 3]

In [ ]:
# converting the list to np array
np_car_brands = np.array(car_brands)
np_num_cylinders = np.array(num_cylinders)
print('np array:',np_car_brands )
print('np array:',np_num_cylinders)
type(np_num_cylinders)

np array: ['Mercedies' 'BMW' 'Audi' 'Feerai' 'Tesla']
np array: [5 4 6 7 3]


numpy.ndarray

In [ ]:
#np matrix - creating rows and columns, matix is created using list of list
matrix = np.array([['Name','Age','Marks'],['Mayank',str(32),str(90)],['Ravi',str(33),str(80)]])
print(matrix)
type(matrix)

[['Name' 'Age' 'Marks']
 ['Mayank' '32' '90']
 ['Ravi' '33' '80']]


numpy.ndarray

In [ ]:
import numpy as np
sports = ['Cricket', 'Football', 'Tennis', 'Golf', 'Baseball']
sports_new = np.array(sports)
print(sports_new)
type(sports_new)

['Cricket' 'Football' 'Tennis' 'Golf' 'Baseball']


numpy.ndarray

In [ ]:
#creating a np of Employee name, Employee ID, Department, Blood group (creating matrix - 2D np array- rows and columns)
import numpy as np
np_Employee_desciption = np.array([['Employee name','Employee ID','Department','Blood group'],['Mayank Sharma',str(1),'R&D','O+ve'],['Smitha Rachapalli',str(2),'R&D','O+ve'],['Rohini Begapalli',str(3),'R&D','O+ve']])
np_Employee_desciption

array([['Employee name', 'Employee ID', 'Department', 'Blood group'],
       ['Mayank Sharma', '1', 'R&D', 'O+ve'],
       ['Smitha Rachapalli', '2', 'R&D', 'O+ve'],
       ['Rohini Begapalli', '3', 'R&D', 'O+ve']], dtype='<U17')

##1.2) NumPy functions

In [ ]:
# arange (arr) functions can create an array containg start, stop and step size (default step size is 1). First number is included and last number is excluded
#eg- make a np array of numbers from 1 to 10
arr1 = np.arange(0,11)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#eg- make a np array of numbers from 1 to 10 with step size or gap of 2, np array of all even numbers from 1 to 10
arr1 = np.arange(0,11,2)
arr1

array([ 0,  2,  4,  6,  8, 10])

In [ ]:
#eg- make a np array of numbers from 1 to 10 with step size or gap of 3
arr1 = np.arange(0,11,3)
arr1

array([0, 3, 6, 9])

In [ ]:
#linspace include the last number and stop there.
arr1 = np.linspace(0,10)
arr1

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
#linspace include the last number and stop there.
arr1 = np.linspace(0,10,5)
arr1

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
#linspace include the last number and stop there.
arr1 = np.linspace(0,11,5)
arr1

array([ 0.  ,  2.75,  5.5 ,  8.25, 11.  ])

In [ ]:
#np.zeros will initialise all the elements to zero, eg- it has 3 rows and 4 columns initialize with zero
arr1 = np.zeros([3,4])
arr1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#np.zeros will initialise all the elements to zero, eg- it has 3 rows and 4 columns initialize with ones
arr1 = np.ones([3,4])
arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
#np.eye() creates an identity matrix where number of rows and columns are same, its a square. It has zero everywhere except 1 in diagonal. values are float
arr1 = np.eye(4)
arr1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
vec = np.zeros([2,3])
print(vec)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
num_list1= [1,2,3,4,5,6]
np_num_list1 =np.array(num_list1)
print(np_num_list1)

[1 2 3 4 5 6]


In [ ]:
num_list2 = [7,8,9,10,11,12]
np_num_list2 = np.array(num_list2)
print(np_num_list2)

[ 7  8  9 10 11 12]


In [ ]:
arr1= np.array([['Mayank','Mohan'],['BMW','Jacquar'],[1,2]])
print(arr1)

[['Mayank' 'Mohan']
 ['BMW' 'Jacquar']
 ['1' '2']]


In [ ]:
arr1 =np.arange(0,9)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# to reshape the arry we use reshape function
arr2 = arr1.reshape(3,3)
arr2

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr3 = np.arange(0,10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
reshape_arr3 = arr3.reshape(2,5)
reshape_arr3

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
reshape_arr3 = arr3.reshape(5,2)
reshape_arr3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
# reshape function maintain the original dimension of old array while reshaping content from old array to new array whoes dimension is changed
reshape_arr3 = arr3.reshape(5,2)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
reshape_arr3 = arr3.reshape(5,2)
reshape_arr3

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
# cannot reshape array of size 10 into shape (2,3)
arr4 = np.arange(0,10)
reshape_arr4 = arr4.reshape(2,3)

ValueError: cannot reshape array of size 10 into shape (2,3)

In [ ]:
# Arthmetic operations in NumPy. It performs Trigonometric, Exponents and Logarithmic functions.
# Trigonometric operations- sin,cos,tan
print('Sin of 4 is ',np.sin(4))
print('Cos of 4 is ',np.cos(4))
print('Tan of 4 is ',np.tan(4))

Sin of 4 is  -0.7568024953079282
Cos of 4 is  -0.6536436208636119
Tan of 4 is  1.1578212823495775


In [ ]:
print('Sin of 4 is ',np.sin(arr4))
print('Cos of 4 is ',np.cos(arr4))
print('Tan of 4 is ',np.tan(arr4))

Sin of 4 is  [ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
Cos of 4 is  [ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026]
Tan of 4 is  [ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501
 -0.29100619  0.87144798 -6.79971146 -0.45231566]


In [ ]:
#exponent- e to the power exponent, eg- here e to the power 2
np.exp(2)

7.38905609893065

In [ ]:
# e to the power 2,4,6
arr5 = ([2,4,6])
np.exp(arr5)

array([  7.3890561 ,  54.59815003, 403.42879349])

In [ ]:
# logarithmic function- Numpy automatically takes base of log as e, eg- log base e 2
np.log(2)

0.6931471805599453

In [ ]:
np.log(arr5)

array([0.69314718, 1.38629436, 1.79175947])

In [ ]:
##log with base 10
np.log10(2)

0.3010299956639812

In [ ]:
# performing mathematical operations-
arr7 = np.arange(1,6)
arr8 = np.arange(6,11)
print(arr7)
print(arr8)
print(arr7+arr8) #addition
print(arr8-arr7) #substraction
print(arr7*arr8) #multiplication
print(arr7/arr8) #division
print(1/arr7) # for inverse 1 /1,1/2,1/3,1/3,1/5
print(arr7**arr8) # for power
print(6%2) # for remainder

[1 2 3 4 5]
[ 6  7  8  9 10]
[ 7  9 11 13 15]
[5 5 5 5 5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
[1.         0.5        0.33333333 0.25       0.2       ]
[      1     128    6561  262144 9765625]
0


In [ ]:
#operations on matrix
matrix3 = np.arange(1,10).reshape(3,3)
print(matrix3)
matrix4 = np.eye(3)
print(matrix4)
print('Addition \n', matrix3+matrix4)
print('Substraction \n', matrix3-matrix4)
print('Multiplication \n', matrix3*matrix4)
print('Division \n', matrix3/matrix4) #number/0 is inf infinity

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Addition 
 [[ 2.  2.  3.]
 [ 4.  6.  6.]
 [ 7.  8. 10.]]
Substraction 
 [[0. 2. 3.]
 [4. 4. 6.]
 [7. 8. 8.]]
Multiplication 
 [[1. 0. 0.]
 [0. 5. 0.]
 [0. 0. 9.]]
Division 
 [[ 1. inf inf]
 [inf  5. inf]
 [inf inf  9.]]


<ipython-input-76-d4a09c99489a>:9: RuntimeWarning: divide by zero encountered in divide
  print('Division \n', matrix3/matrix4) #number/0 is inf infinity


Runtimewarning: Error occur during program execution (run-time), after sucessful complilation. Division error is the common error. integer/0 error gives infinity (inf) value as this is not a defined operation.

In [ ]:
# Linear Algebra matrix multiplication calculation-
import numpy as np
matrix5 = np.arange(1,10).reshape(3,3)
print(matrix5)
matrix6 = np.arange(11,20).reshape(3,3)
print(matrix6)
print('Multiplication:\n', matrix5 @ matrix6) # dot product(@) linear algebra matrix multiplication

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
Multiplication:
 [[ 90  96 102]
 [216 231 246]
 [342 366 390]]


In [ ]:
#Transpose function
print(matrix5)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
np.transpose(matrix5) #Transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
matrix5.T #Transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
matrix5.t #in Transpose 'T' has to be capital not small font.

AttributeError: 'numpy.ndarray' object has no attribute 't'

In [ ]:
# to find minimum and maximum
a = np.min(matrix5)
b= np.max(matrix5)
print(a)
print(b)

1
9


In [ ]:
# generating a random numbers in Numpy using np.random.rand in array
import numpy as np
a = np.random.rand(6)
print(a)
b = np.random.rand(3,3) # generating a random numbers in Numpy using np.random.rand in matrix
print(b)

[0.79385721 0.18970898 0.61298346 0.60210853 0.88901748 0.4123095 ]
[[0.64862422 0.02763678 0.40052684]
 [0.87317184 0.99242221 0.89391557]
 [0.59293358 0.22148097 0.8097176 ]]


In [ ]:
# generating a standard normal random numbers in Numpy using np.random.randn in array means mean = 0 and variance = 1, also called as guassian distribution
a_n = np.random.randn(6)
print(a_n)
b_n = np.random.randn(3,3) # generating a standard normal random numbers in Numpy using np.random.randn in matrix means mean = 0 and variance = 1, also called as guassian distribution
print(b_n)

[-0.63960097  0.60266873  0.85279539 -1.66674551  0.11178989  1.04905119]
[[-0.18515207  0.20464635 -0.89550531]
 [-0.80136032  1.02895848  2.11399089]
 [ 1.54185643  0.96378237  0.8306337 ]]


In [ ]:
# to calculate mean we use np.mean function, mean is a mesaure of central tendency, mean is calculated as sum of all the values/ total number of values
c = np.arange(1,11)
print(c)
print('The mean of c is:', np.mean(c)) # here mean is = (1+2+3+4+4+6+7+8=9=10)/10
print('The median of c is:', np.median(c)) # median is the central value so here median is = (5+6)/2
d = np.arange(1,11).reshape(2,5) # to reshape the array
print(d)
print('The standard deviation of c is', np.std(c)) # to calculate standard deviation

[ 1  2  3  4  5  6  7  8  9 10]
The mean of c is: 5.5
The median of c is: 5.5
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
The standard deviation of c is 2.8722813232690143


In [ ]:
import numpy as np
# generating random values in array
e = np.random.randint(1,5,10)
print(e)

[1 3 1 3 4 1 4 1 1 2]


In [ ]:
# generating random values in matrix
f = np.random.randint(1,5,[2,2])
print(f)

[[1 1]
 [2 4]]


In [ ]:
mat1 = np.arange(-9,0,1).reshape(3,3)
print(mat1)
print(np.min(mat1))
print(np.max(mat1))

[[-9 -8 -7]
 [-6 -5 -4]
 [-3 -2 -1]]
-9
-1


##1.3) Acessing entries of a NumPy Array

In [ ]:
#acessing entries in numpy array - we have to mention index number in square brackets
import numpy as np
a = np.arange(1,11)
print(a)
print(a[1])
print(a[0:3])

[ 1  2  3  4  5  6  7  8  9 10]
2
[1 2 3]


In [ ]:
# acessing array greater than some value, eg - here greater than 5
print(a[a>5])

[ 6  7  8  9 10]


In [ ]:
# acessing array lesser than some value, eg - here less than 2
print(a[a<2])

[1]


In [ ]:
# acessing arrays
b = np.random.randn(10) # generate a random list of numbers till 10.
print(b)

[ 1.6115435   0.1981902   0.66467784  1.30449585  0.31338347 -0.73459828
  0.63876893  1.45358763 -0.47526046 -0.24145608]


In [ ]:
print(b[0])
print(b[1:3])
print(b[-2])
print(b[np.arange(2,8,3)])# acessing multiple non-consecutive entry using np.arange function, acessing random numbers
print('Index values to access:', np.arange(2,8,3))

1.611543496554191
[0.1981902  0.66467784]
-0.47526046290232954
[ 0.66467784 -0.73459828]
Index values to access: [2 5]


In [ ]:
print(b[b>0.8])
b>0.8 # in boolean format - true or false

[1.6115435  1.30449585 1.45358763]


array([ True, False, False,  True, False, False, False,  True, False,
       False])

In [ ]:
#accessing values in matrix
import numpy as np
matrix1= np.random.randn(5,5)
print(matrix1) #this will generate the matrix arry of random numbers in 5 rows and 5 columns
print(matrix1 [1]) # to access the values in row, here 0 index is first row, 1 index is 2nd row, 2 index is 3rd row etc.
print(matrix1[1][0]) # to access the value in row
print(matrix1[1,0]) # to access the value in row

[[-1.03572458  0.54855298  0.04006552 -1.30480268  0.89024756]
 [ 1.15845584  0.29980255 -1.17511831 -1.30449924  1.44962644]
 [ 0.11633507  1.723392    1.27871711  1.19439044  0.58958359]
 [ 0.82945197  0.61482179 -0.83979781  0.67968766 -1.05614261]
 [ 0.67872154  0.94380461 -0.06938411 -0.32110271 -0.36470403]]
[ 1.15845584  0.29980255 -1.17511831 -1.30449924  1.44962644]
1.1584558397566713
1.1584558397566713


In [ ]:
#accesing first two rows with second and third column
print(matrix1[0:2,1:3])
print('The values greater than zero:\n',matrix1[matrix1>0]) # to access the values greater than 0, this will destory the matrix and bring them in arry format
print('The values lesser than zero:\n',matrix1[matrix1<0]) # to access the values lesser than 0, this will destory the matrix and bring them in arry format

[[ 0.54855298  0.04006552]
 [ 0.29980255 -1.17511831]]
The values greater than zero:
 [0.54855298 0.04006552 0.89024756 1.15845584 0.29980255 1.44962644
 0.11633507 1.723392   1.27871711 1.19439044 0.58958359 0.82945197
 0.61482179 0.67968766 0.67872154 0.94380461]
The values lesser than zero:
 [-1.03572458 -1.30480268 -1.17511831 -1.30449924 -0.83979781 -1.05614261
 -0.06938411 -0.32110271 -0.36470403]


##1.4) Modifying entries in Numpy array

In [ ]:
# Modifing entries in array
rand_arr= np.random.randn(10)
print('The random array unmodified:\n',rand_arr)
rand_arr[1] = 2 # asigning one value
print('The random array modified in second position, index-1:\n', rand_arr)
rand_arr[0:3] = 5 # replacing more than one values in list with one value
print('The random array modified from first (index-0) to third (index-2) position,:\n', rand_arr)
rand_arr[0:3] = 5,6,7 # replacing more than one values in list with more than one value
print('The random array modified from first (index-0) to third (index-2) position,:\n', rand_arr)
rand_arr[0:3] = 5,6 # replacing more than one values in list with more than one value, error message will pop up if we replace 3 values from more than 3 values or less than 3 values
print('The random array modified from first (index-0) to third (index-2) position,:\n', rand_arr)

The random array unmodified:
 [-0.63452187 -1.31062381 -0.23644068 -0.16767229 -0.18645547  0.52951894
 -0.0133031   0.59693912 -2.00296464 -0.48890156]
The random array modified in second position, index-1:
 [-0.63452187  2.         -0.23644068 -0.16767229 -0.18645547  0.52951894
 -0.0133031   0.59693912 -2.00296464 -0.48890156]
The random array modified from first (index-0) to third (index-2) position,:
 [ 5.          5.          5.         -0.16767229 -0.18645547  0.52951894
 -0.0133031   0.59693912 -2.00296464 -0.48890156]
The random array modified from first (index-0) to third (index-2) position,:
 [ 5.          6.          7.         -0.16767229 -0.18645547  0.52951894
 -0.0133031   0.59693912 -2.00296464 -0.48890156]


ValueError: could not broadcast input array from shape (2,) into shape (3,)

In [ ]:
#modifing values based on logical references
print(rand_arr[rand_arr>0])
rand_arr>0 # in boolean format

[5.         6.         7.         0.52951894 0.59693912]


array([ True,  True,  True, False, False,  True, False,  True, False,
       False])

In [ ]:
vec1 = np.array([4, 7, 8, 9, 10, 6, 1]) # replacing values with 2 if the values are greater than 6
vec1[vec1>6] = 2
print(vec1)

[4 2 2 2 2 6 1]


##1.5) Modifying entries in Numpy array- matrix

In [ ]:
rand_mat1 = np.random.randn(5,5)
print('The values before modifications:\n',rand_mat1)
rand_mat1[1:4,1:4]=5 #modifying value to 5 from rows 2,3 and 4 (index-1,2 and 3), column 2,3 and 4 (index-1 to 4), first index value is included while last index value is excluded.
print('The values after modifications:\n',rand_mat1)
print('The values of row 1 and 2, column 2 and 3 are:\n',rand_mat1[0:2,1:3]) #accesing multiple entries- row-1(index 0), row-2(index 1), column-2(index 1), column-3(index 2), in [0:2,1:3] 0 and 1 index is included and 2 and 3 index is excluded.

The values before modifications:
 [[ 0.72792957  1.64882363  1.46360822 -1.51744686 -1.17997512]
 [-0.56842687  1.31124623 -0.93989359  0.24913591 -1.59466475]
 [ 0.43721517  0.30092765  0.49200243 -1.35233563  0.0094191 ]
 [ 1.40283812  0.72871301  0.04828158 -0.03973975  0.11808793]
 [ 0.03816418  0.54053448  0.69366015 -0.60989976 -0.2364193 ]]
The values after modifications:
 [[ 0.72792957  1.64882363  1.46360822 -1.51744686 -1.17997512]
 [-0.56842687  5.          5.          5.         -1.59466475]
 [ 0.43721517  5.          5.          5.          0.0094191 ]
 [ 1.40283812  5.          5.          5.          0.11808793]
 [ 0.03816418  0.54053448  0.69366015 -0.60989976 -0.2364193 ]]
The values of row 1 and 2, column 2 and 3 are:
 [[1.64882363 1.46360822]
 [5.         5.        ]]


In [ ]:
# creating sub-matrix from main matrix, making sub-matrix of first 3 rows
sub_matrix1 = rand_mat1[0:3,0:5]
print('The unmodified sub-matrix1 created from main matrix:\n',sub_matrix1)
# Modify all the values to 3 in sub-matrix1
sub_matrix1[:] = 3
print('The modified sub-matrix1 created from main matrix:\n',sub_matrix1)

The unmodified sub-matrix1 created from main matrix:
 [[ 0.72792957  1.64882363  1.46360822 -1.51744686 -1.17997512]
 [-0.56842687  5.          5.          5.         -1.59466475]
 [ 0.43721517  5.          5.          5.          0.0094191 ]]
The modified sub-matrix1 created from main matrix:
 [[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]


In [ ]:
rand_mat1 # main matrix also got changed once we modify the sub-matrix!

array([[ 3.        ,  3.        ,  3.        ,  3.        ,  3.        ],
       [ 3.        ,  3.        ,  3.        ,  3.        ,  3.        ],
       [ 3.        ,  3.        ,  3.        ,  3.        ,  3.        ],
       [ 1.40283812,  5.        ,  5.        ,  5.        ,  0.11808793],
       [ 0.03816418,  0.54053448,  0.69366015, -0.60989976, -0.2364193 ]])

In [ ]:
# to avoid such changes we have to apply .copy() method when we assign sub-matrix
random_matrix2= np.random.randn(6,6)
print('The raw data of random matrix2:\n',random_matrix2)
sub_matrix1= random_matrix2[0:3,0:7].copy() # making random_matrix2 (main matrix) unmodified
print('The raw data of sub-matrix1:\n',sub_matrix1)
sub_matrix1[:]=5
print('The modified sub-matrix1:\n',sub_matrix1)
print('The main matrix:\n',random_matrix2)

The raw data of random matrix2:
 [[-0.02984812 -0.95445347  0.91808908  0.45481814 -0.08249463 -0.06119251]
 [ 0.14286136 -0.79355424 -0.13971298 -0.74785815 -1.16105735  0.39853517]
 [ 2.78324465  0.34688493  0.66199787 -0.63758977 -0.70337923  0.69506074]
 [-0.7798045   0.43610657 -1.53452709  0.2635757  -2.54540062  0.18486698]
 [-0.15285622 -0.57678841 -0.17667318 -0.69452407  0.499637   -0.9507182 ]
 [ 1.58799643  0.53821223  0.45256719 -1.14438833 -2.08178149 -1.43470725]]
The raw data of sub-matrix1:
 [[-0.02984812 -0.95445347  0.91808908  0.45481814 -0.08249463 -0.06119251]
 [ 0.14286136 -0.79355424 -0.13971298 -0.74785815 -1.16105735  0.39853517]
 [ 2.78324465  0.34688493  0.66199787 -0.63758977 -0.70337923  0.69506074]]
The modified sub-matrix1:
 [[5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5. 5.]]
The main matrix:
 [[-0.02984812 -0.95445347  0.91808908  0.45481814 -0.08249463 -0.06119251]
 [ 0.14286136 -0.79355424 -0.13971298 -0.74785815 -1.16105735  0.39853517]
 

##1.6) Saving and Loading Numpy array

In [ ]:
from google.colab import drive # if we are running Numpy in Google Colab and want to save in Google Drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
#creating random matrix
import numpy as np
matrix3= np.random.randint(1,10,10).reshape(2,5)
print('The matrix3:\n',matrix3)
matrix4= np.random.randint(10,20,10).reshape(2,5)
print('The matrix4:\n',matrix4)

The matrix3:
 [[6 9 3 9 4]
 [2 9 6 9 4]]
The matrix4:
 [[10 11 12 12 10]
 [18 19 18 13 16]]


In [ ]:
# using np.save() function
import numpy as np
np.save('matrix3.npy',matrix3)
np.save('matrix4.npy',matrix4)

In [ ]:
# to save multiple numpy array files we use np.savez()
np.savez('matrix_files.npz',matrix3,matrix4)

In [ ]:
# to load the file np.load()
loaded_matrix3 = np.load('matrix3.npy')
print('The loaded matrix3 is \n',loaded_matrix3)
loaded_matrix4 = np.load('matrix4.npy')
print('The loaded matrix4 is \n',loaded_matrix4)
loaded_multiple_files = np.load('matrix_files.npz')
print('The loaded multiple files is \n',loaded_multiple_files)

The loaded matrix3 is 
 [[6 9 3 9 4]
 [2 9 6 9 4]]
The loaded matrix4 is 
 [[10 11 12 12 10]
 [18 19 18 13 16]]
The loaded multiple files is 
 NpzFile 'matrix_files.npz' with keys: arr_0, arr_1


In [ ]:
print(matrix_files.npz[arr0,arr_1])

NameError: name 'matrix_files' is not defined

In [ ]:
#to can save or load text files but only single variable we use text(txt) function, eg- if we save a numpy in python and want to open with MS Excel or R. This will make the file universal and can open in non-python environmnet
np.savetxt('matrix3.txt',matrix3,delimiter=',')
np.savetxt('matrix4.txt',matrix4,delimiter=',')
rand_mat_text3= np.loadtxt('matrix3.txt',delimiter=',')
print('rand_mat_text3 is:\n',rand_mat_text3)
rand_mat_text4= np.loadtxt('matrix4.txt',delimiter=',')
print('rand_mat_text4 is:\n',rand_mat_text4)

rand_mat_text3 is:
 [[6. 9. 3. 9. 4.]
 [2. 9. 6. 9. 4.]]
rand_mat_text4 is:
 [[10. 11. 12. 12. 10.]
 [18. 19. 18. 13. 16.]]


#2) Pandas

In [ ]:
# importing pandas library
import pandas as pd
import numpy as np

##2.1) Pandas - Series and DataFrames
Panda Series is a one dimensional labeled array or list capable of holding any type of data (integer,float,string,boolean,python objects etc). The labels are collectively called as index. Panda series can be thought as a single column of excel spreadsheet and each entry in a series corresponds to an individual row in the spreadsheet. Pandas is used to create and manipulate data sets. It create a data sets or series like NumPy series(array and matrix). Its like an excel sheet in python.

In [ ]:
#Panda Series
#creating list of prices of different medicines
med_price_list = [100,200,250,600,800]
print('Med_price_list: ', med_price_list)

# converting med_price_list to array
med_price_arr = np.array(med_price_list)
print('Med_price_array: ', med_price_arr)

# converting list and array into Pandas Series objects
pd_series_list = pd.Series(med_price_list)
print('pd_series_list:\n', pd_series_list)
pd_series_arr = pd.Series(med_price_arr)
print('pd_series_arr:\n', pd_series_arr)
type(pd_series_list)

Med_price_list:  [100, 200, 250, 600, 800]
Med_price_array:  [100 200 250 600 800]
pd_series_list:
 0    100
1    200
2    250
3    600
4    800
dtype: int64
pd_series_arr:
 0    100
1    200
2    250
3    600
4    800
dtype: int64


pandas.core.series.Series

In [ ]:
# genertaing strings data type in pd series
med_price_list_labeled = pd.Series(med_price_list, index = ['Dolo650','Cetrizine','Augmentin','Ibuprofin','Pantop'])
print('med_price_list_labeled:\n', med_price_list_labeled)

med_price_list_labeled:
 Dolo650      100
Cetrizine    200
Augmentin    250
Ibuprofin    600
Pantop       800
dtype: int64


In [ ]:
# adding 2.5 to existing price list
updated_med_price_list_labeled = med_price_list_labeled + 2.5
print(updated_med_price_list_labeled)

Dolo650      102.5
Cetrizine    202.5
Augmentin    252.5
Ibuprofin    602.5
Pantop       802.5
dtype: float64


In [ ]:
# calculate the difference between two price list
new_price_list = [120,250,300,680,900]
new_med_price_list_labeled = pd.Series(new_price_list,index = ['Dolo650','Cetrizine','Augmentin','Ibuprofin','Pantop'])
print('new_med_price_list_labeled:\n', new_med_price_list_labeled)
print('Difference between the prices of medicine-\n',new_med_price_list_labeled - updated_med_price_list_labeled)
new_med_price_list_labeled[0] # indexing

new_med_price_list_labeled:
 Dolo650      120
Cetrizine    250
Augmentin    300
Ibuprofin    680
Pantop       900
dtype: int64
Difference between the prices of medicine-
 Dolo650      17.5
Cetrizine    47.5
Augmentin    47.5
Ibuprofin    77.5
Pantop       97.5
dtype: float64


<ipython-input-119-1d22ac59c652>:6: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  new_med_price_list_labeled[0] # indexing


120

In [ ]:
# Pandas DataFrame- DataFrame generates two dimensional data structure with labeled axes (rows and columns)
# creating Pandas DataFrame using list
student = ['Mayank','Vishal','Vikas','Rohit','Abhay']
df1 = pd.DataFrame(student,columns=['Students'])
df1

Students
0   Mayank
1   Vishal
2    Vikas
3    Rohit
4    Abhay

In [ ]:
#creating Pandas DataFrame using dictonary
grades = ['A+','A','B','B+','C']
age = [20,20,21,22,21]
marks = [80,100,40,60,55]
df2 = pd.DataFrame({'Students':student,'Grades':grades,'Age':age,'Marks':marks})
df2

Students Grades  Age  Marks
0   Mayank     A+   20     80
1   Vishal      A   20    100
2    Vikas      B   21     40
3    Rohit     B+   22     60
4    Abhay      C   21     55

In [ ]:
#calculating mesures of central tendency (mean, median, mode and standard deviation) in DataFrame
df2['Marks'].mean()
print('Mean of marks: ',df2['Marks'].mean())
df2['Marks'].median()
print('Median of marks: ',df2['Marks'].median())
df2['Marks'].mode()
print('Mode of marks:\n',df2['Marks'].mode())
df2['Marks'].std()
print('Standard deviation of marks: ',df2['Marks'].std())
df2

Mean of marks:  67.0
Median of marks:  60.0
Mode of marks:
 0     40
1     55
2     60
3     80
4    100
Name: Marks, dtype: int64
Standard deviation of marks:  23.345235059857504


Students Grades  Age  Marks
0   Mayank     A+   20     80
1   Vishal      A   20    100
2    Vikas      B   21     40
3    Rohit     B+   22     60
4    Abhay      C   21     55

In [ ]:
# creating DataFrame using panda series
# Data for total energy consumption in USA was collected in 2012-2018, present the data in DataFrame
year = pd.Series([2012,2013,2014,2015,2016,2017,2018])
energy_consumption = pd.Series([2152,2196,2020,2030,2019,2060,3000])
df3 = pd.DataFrame({'Year':year,'Energy consumption(Mtoe)':energy_consumption})
df3

Year  Energy consumption(Mtoe)
0  2012                      2152
1  2013                      2196
2  2014                      2020
3  2015                      2030
4  2016                      2019
5  2017                      2060
6  2018                      3000

In [ ]:
# generating DataFrame using numpy array
df4 = pd.DataFrame(np.random.rand(5,2), columns= ['Trail-1','Trail-2'])
df4

Trail-1   Trail-2
0  0.347193  0.570513
1  0.722814  0.168687
2  0.042186  0.723429
3  0.760901  0.313362
4  0.232662  0.579233

In [ ]:
# Generate a DataFrame of CHO cell batch representing cell count, percentage viability over batch monitoring
Day = [1,2,3,4,5,6,7,8,9,10,11,12,13,14]
Percentage_viability = [100,100,99,98,98,97,95,94.2,91,89,85,83,80,79.8]
Cell_count = [4,6,8.9,10,11,13,15,18,19.1,20,19.6,18,17.2,13]
df5 = pd.DataFrame({'Day':Day,'Percentage viability':Percentage_viability,'Cell count(X10^6) cells/ml':Cell_count})
df5

Day  Percentage viability  Cell count(X10^6) cells/ml
0     1                 100.0                         4.0
1     2                 100.0                         6.0
2     3                  99.0                         8.9
3     4                  98.0                        10.0
4     5                  98.0                        11.0
5     6                  97.0                        13.0
6     7                  95.0                        15.0
7     8                  94.2                        18.0
8     9                  91.0                        19.1
9    10                  89.0                        20.0
10   11                  85.0                        19.6
11   12                  83.0                        18.0
12   13                  80.0                        17.2
13   14                  79.8                        13.0

##2.2) Acessing and Modifing Panda Series

In [ ]:
# List of different telecomunications in US and revenue generated from them in 2020
Operators = ['AT&T','Verizon', 'T-Mobile US','US Cellular']
Revenues = [171.76,128.29,68.4,4.04]
#creating a pandas series
telecom = pd.Series(Revenues,index= Operators)
telecom

AT&T           171.76
Verizon        128.29
T-Mobile US     68.40
US Cellular      4.04
dtype: float64

In [ ]:
telecom[0]

<ipython-input-6-2a8cd70c385e>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  telecom[0]


171.76

In [ ]:
telecom[-1]

<ipython-input-7-2b9e82d1cf78>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  telecom[-1]


4.04

In [ ]:
telecom[0:3]

AT&T           171.76
Verizon        128.29
T-Mobile US     68.40
dtype: float64

In [ ]:
telecom[:3] # if we dont put any number before colon, python will consider it to be zero index

AT&T           171.76
Verizon        128.29
T-Mobile US     68.40
dtype: float64

In [ ]:
telecom[-3:] # if we dont put any number after colon, python will consider it to be last index

Verizon        128.29
T-Mobile US     68.40
US Cellular      4.04
dtype: float64

In [ ]:
telecom['T-Mobile US'] # Acessing entries based on labeled index

68.4

In [ ]:
telecom[[0,2,3]] # getting individual multiple entry

<ipython-input-12-5a08c4786412>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  telecom[[0,2,3]] # getting individual multiple entry


AT&T           171.76
T-Mobile US     68.40
US Cellular      4.04
dtype: float64

In [ ]:
telecom[:'T-Mobile US'] # getting multiple entries based on labeled index, if we put labeled index after colon, python will include that, unlike earlier cases where first index is included and last index is excluded

AT&T           171.76
Verizon        128.29
T-Mobile US     68.40
dtype: float64

In [ ]:
telecom[:2]
telecom

AT&T           171.76
Verizon        128.29
T-Mobile US     68.40
US Cellular      4.04
dtype: float64

In [ ]:
telecom[-1] = 100 # modifying entries in series
print(telecom)

AT&T           171.76
Verizon        128.29
T-Mobile US     68.40
US Cellular    100.00
dtype: float64


<ipython-input-15-4586913c9ed7>:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  telecom[-1] = 100 # modifying entries in series


##2.3) Accesing Pandas DataFrame

In [ ]:
# creating pandas DataFrame of 24/7 strore inventory list containing customer visits, inventory list contains customerID,Location,gender of customer,type of product purchased, quantitiy of products purchasedn and total bill amount.
Store_data = pd.DataFrame({'CustomerID':['Cust00','Cust01','Cust02','Cust03','Cust04'],
                           'Location':['Chicago','London','Boston','Tokyo','Delhi'],
                           'Gender':['M','F','M','F','F'],
                           'Product type':['Electronics','Food and Beverages','Electronics','Electronics','Food and Beverages'],
                           'Quantity':[2,5,2,1,7],
                           'Total Bill Amount in $':[500,200,260,200,1000]})
Store_data

CustomerID Location Gender        Product type  Quantity  \
0     Cust00  Chicago      M         Electronics         2   
1     Cust01   London      F  Food and Beverages         5   
2     Cust02   Boston      M         Electronics         2   
3     Cust03    Tokyo      F         Electronics         1   
4     Cust04    Delhi      F  Food and Beverages         7   

   Total Bill Amount in $  
0                     500  
1                     200  
2                     260  
3                     200  
4                    1000

In [ ]:
Store_data[0:2]# in dataframe to access we have to write index with colon(:), single index value without colon is not considered

CustomerID Location Gender        Product type  Quantity  \
0     Cust00  Chicago      M         Electronics         2   
1     Cust01   London      F  Food and Beverages         5   

   Total Bill Amount in $  
0                     500  
1                     200

In [ ]:
Store_data[-2:]

CustomerID Location Gender        Product type  Quantity  \
3     Cust03    Tokyo      F         Electronics         1   
4     Cust04    Delhi      F  Food and Beverages         7   

   Total Bill Amount in $  
3                     200  
4                    1000

In [ ]:
Store_data['Location'] # to access entire column via column index

0    Chicago
1     London
2     Boston
3      Tokyo
4      Delhi
Name: Location, dtype: object

In [ ]:
Store_data[::2] # accesing data with gap or step size of 2

CustomerID Location Gender        Product type  Quantity  \
0     Cust00  Chicago      M         Electronics         2   
2     Cust02   Boston      M         Electronics         2   
4     Cust04    Delhi      F  Food and Beverages         7   

   Total Bill Amount in $  
0                     500  
2                     260  
4                    1000

In [ ]:
Store_data[::-1] # accesing data in reverse order

CustomerID Location Gender        Product type  Quantity  \
4     Cust04    Delhi      F  Food and Beverages         7   
3     Cust03    Tokyo      F         Electronics         1   
2     Cust02   Boston      M         Electronics         2   
1     Cust01   London      F  Food and Beverages         5   
0     Cust00  Chicago      M         Electronics         2   

   Total Bill Amount in $  
4                    1000  
3                     200  
2                     260  
1                     200  
0                     500

In [ ]:
Store_data[::-2] # accesing data in reverse order with gap of 2

CustomerID Location Gender        Product type  Quantity  \
4     Cust04    Delhi      F  Food and Beverages         7   
2     Cust02   Boston      M         Electronics         2   
0     Cust00  Chicago      M         Electronics         2   

   Total Bill Amount in $  
4                    1000  
2                     260  
0                     500

##2.4) Acessing and Modifying DataFrame (loc and iloc)

In [ ]:
Store_data.loc[0] # loc is used to access individual contents, here it can be used with index numbers and column name, DataFrame.loc[[index number],[column name]] or DataFrame.loc[index number], here if we rae specifying woth index numbers and column name than row comes first and column comes second- DataFrame.loc[[rows index],[column name]]

CustomerID                     Cust00
Location                      Chicago
Gender                              M
Product type              Electronics
Quantity                            2
Total Bill Amount in $            500
Name: 0, dtype: object

In [ ]:
Store_data.loc[0:2]

CustomerID Location Gender        Product type  Quantity  \
0     Cust00  Chicago      M         Electronics         2   
1     Cust01   London      F  Food and Beverages         5   
2     Cust02   Boston      M         Electronics         2   

   Total Bill Amount in $  
0                     500  
1                     200  
2                     260

In [ ]:
Store_data.loc[[0,1,2],['Location','Gender']]

Location Gender
0  Chicago      M
1   London      F
2   Boston      M

In [ ]:
Store_data.loc[[0,2],['Location','Gender']]

Location Gender
0  Chicago      M
2   Boston      M

In [ ]:
Store_data.iloc[[0,1,2],[0,1,2]] # iloc is used to access individual contents by index numbers [[row numbers],[column numbers]]

CustomerID Location Gender
0     Cust00  Chicago      M
1     Cust01   London      F
2     Cust02   Boston      M

In [ ]:
Store_data.iloc[[0:2],[0:2]]

SyntaxError: invalid syntax (<ipython-input-28-f4f5fbe7b494>, line 1)

In [ ]:
Store_data.loc[[3],['Product type']]

Product type
3  Electronics

In [ ]:
# to change entry, Electronics to Dairy in Product type column
Store_data.loc[[3],['Product type']] = 'Dairy'
Store_data

CustomerID Location Gender        Product type  Quantity  \
0     Cust00  Chicago      M         Electronics         2   
1     Cust01   London      F  Food and Beverages         5   
2     Cust02   Boston      M         Electronics         2   
3     Cust03    Tokyo      F               Dairy         1   
4     Cust04    Delhi      F  Food and Beverages         7   

   Total Bill Amount in $  
0                     500  
1                     200  
2                     260  
3                     200  
4                    1000

In [ ]:
Store_data.loc[[3],['Product type']] = 'Electronics' # reversing the modified entry using loc and iloc function
Store_data

CustomerID Location Gender        Product type  Quantity  \
0     Cust00  Chicago      M         Electronics         2   
1     Cust01   London      F  Food and Beverages         5   
2     Cust02   Boston      M         Electronics         2   
3     Cust03    Tokyo      F         Electronics         1   
4     Cust04    Delhi      F  Food and Beverages         7   

   Total Bill Amount in $  
0                     500  
1                     200  
2                     260  
3                     200  
4                    1000

In [ ]:
# to change entry, Electronics to Dairy in Product type column
Store_data.loc[[3],['Product type']] = 'Dairy'
Store_data

CustomerID Location Gender        Product type  Quantity  \
0     Cust00  Chicago      M         Electronics         2   
1     Cust01   London      F  Food and Beverages         5   
2     Cust02   Boston      M         Electronics         2   
3     Cust03    Tokyo      F               Dairy         1   
4     Cust04    Delhi      F  Food and Beverages         7   

   Total Bill Amount in $  
0                     500  
1                     200  
2                     260  
3                     200  
4                    1000

In [ ]:
Store_data.iloc[[3],[3]] = 'Electronics'
Store_data

CustomerID Location Gender        Product type  Quantity  \
0     Cust00  Chicago      M         Electronics         2   
1     Cust01   London      F  Food and Beverages         5   
2     Cust02   Boston      M         Electronics         2   
3     Cust03    Tokyo      F         Electronics         1   
4     Cust04    Delhi      F  Food and Beverages         7   

   Total Bill Amount in $  
0                     500  
1                     200  
2                     260  
3                     200  
4                    1000

##2.4)Accesing and Modifying Pandas DataFrames (condition-based indexing)

In [ ]:
Store_data['Quantity']>5

0    False
1    False
2    False
3    False
4     True
Name: Quantity, dtype: bool

In [ ]:
Store_data.loc[Store_data['Quantity']>5]

CustomerID Location Gender        Product type  Quantity  \
4     Cust04    Delhi      F  Food and Beverages         7   

   Total Bill Amount in $  
4                    1000

In [ ]:
# to add a column in DataFrame
Store_data['Rating'] = [1,4,4,5,3]
Store_data

CustomerID Location Gender        Product type  Quantity  \
0     Cust00  Chicago      M         Electronics         2   
1     Cust01   London      F  Food and Beverages         5   
2     Cust02   Boston      M         Electronics         2   
3     Cust03    Tokyo      F         Electronics         1   
4     Cust04    Delhi      F  Food and Beverages         7   

   Total Bill Amount in $  Rating  
0                     500       1  
1                     200       4  
2                     260       4  
3                     200       5  
4                    1000       3

In [ ]:
# to remove a column we use drop function, here first column is axis-0, second column is axis-1, third column is axis-2 etc. We have to define axis number, without correct axis number it will show error. This function doesn't modify the original DataFrame but it creates new DataFrame which excludes the column we want to drop off.
New_DataFrame = Store_data.drop('CustomerID', axis=1)
New_DataFrame

Location Gender        Product type  Quantity  Total Bill Amount in $  \
0  Chicago      M         Electronics         2                     500   
1   London      F  Food and Beverages         5                     200   
2   Boston      M         Electronics         2                     260   
3    Tokyo      F         Electronics         1                     200   
4    Delhi      F  Food and Beverages         7                    1000   

   Rating  
0       1  
1       4  
2       4  
3       5  
4       3

In [ ]:
Store_data # retains the original data in DataFrame

CustomerID Location Gender        Product type  Quantity  \
0     Cust00  Chicago      M         Electronics         2   
1     Cust01   London      F  Food and Beverages         5   
2     Cust02   Boston      M         Electronics         2   
3     Cust03    Tokyo      F         Electronics         1   
4     Cust04    Delhi      F  Food and Beverages         7   

   Total Bill Amount in $  Rating  
0                     500       1  
1                     200       4  
2                     260       4  
3                     200       5  
4                    1000       3

In [ ]:
# if we want drop column in original DataFrame then we should add inplace=True function after axis, here axis= 0 for rows and axis =1 for column
New_DataFrame = Store_data.drop('CustomerID' , axis=1, inplace = True)
print('New_DataFrame:',New_DataFrame)
print('Store_data:',Store_data)

New_DataFrame: None
Store_data:   Location Gender        Product type  Quantity  Total Bill Amount in $  \
0  Chicago      M         Electronics         2                     500   
1   London      F  Food and Beverages         5                     200   
2   Boston      M         Electronics         2                     260   
3    Tokyo      F         Electronics         1                     200   
4    Delhi      F  Food and Beverages         7                    1000   

   Rating  
0       1  
1       4  
2       4  
3       5  
4       3  


In [ ]:
# to drop a row
Store_data.drop(1,axis=0,inplace = True)
Store_data

Location Gender        Product type  Quantity  Total Bill Amount in $  \
0  Chicago      M         Electronics         2                     500   
2   Boston      M         Electronics         2                     260   
3    Tokyo      F         Electronics         1                     200   
4    Delhi      F  Food and Beverages         7                    1000   

   Rating  
0       1  
2       4  
3       5  
4       3

In [ ]:
Store_data.reset_index()

index Location Gender        Product type  Quantity  \
0      0  Chicago      M         Electronics         2   
1      2   Boston      M         Electronics         2   
2      3    Tokyo      F         Electronics         1   
3      4    Delhi      F  Food and Beverages         7   

   Total Bill Amount in $  Rating  
0                     500       1  
1                     260       4  
2                     200       5  
3                    1000       3

In [ ]:
#Practice Exercise
import pandas as pd
# creating pandas DataFrame
Drug1= pd.DataFrame({'Company name':['Biocon','Merck','BIPI','Novo Nordisc','BMS'],
                     'Country':['India','Germany','USA','Denmark','USA'],
                     'Clinical Trials':['Phase-1','Phase-II','Phase-III','Phase-II','Phase-II'],
                     'Side effects':['Mild','None','Lethal','None','None'],
                     'Price in $':[100,200,240,100,250]})
Drug1

Company name  Country Clinical Trials Side effects  Price in $
0        Biocon    India         Phase-1         Mild         100
1         Merck  Germany        Phase-II         None         200
2          BIPI      USA       Phase-III       Lethal         240
3  Novo Nordisc  Denmark        Phase-II         None         100
4           BMS      USA        Phase-II         None         250

In [ ]:
Drug1.sort_values('Price in $',ascending=True) # sort using filter (IMP)

Company name  Country Clinical Trials Side effects  Price in $
0        Biocon    India         Phase-1         Mild         100
3  Novo Nordisc  Denmark        Phase-II         None         100
1         Merck  Germany        Phase-II         None         200
2          BIPI      USA       Phase-III       Lethal         240
4           BMS      USA        Phase-II         None         250

In [ ]:
Drug1.sort_index(ascending=True)

Company name  Country Clinical Trials Side effects  Price in $
0        Biocon    India         Phase-1         Mild         100
1         Merck  Germany        Phase-II         None         200
2          BIPI      USA       Phase-III       Lethal         240
3  Novo Nordisc  Denmark        Phase-II         None         100
4           BMS      USA        Phase-II         None         250

In [ ]:
Drug1.sort_values('Clinical Trials', ascending= True)

Company name  Country Clinical Trials Side effects  Price in $
0        Biocon    India         Phase-1         Mild         100
1         Merck  Germany        Phase-II         None         200
3  Novo Nordisc  Denmark        Phase-II         None         100
4           BMS      USA        Phase-II         None         250
2          BIPI      USA       Phase-III       Lethal         240

In [ ]:
Drug1.iloc[[0],[3]]='Moderate'
Drug1.iloc[[0],[2]] = 'Phase-I'
Drug1

Company name  Country Clinical Trials Side effects  Price in $
0        Biocon    India         Phase-I     Moderate         100
1         Merck  Germany        Phase-II         None         200
2          BIPI      USA       Phase-III       Lethal         240
3  Novo Nordisc  Denmark        Phase-II         None         100
4           BMS      USA        Phase-II         None         250

In [ ]:
Drug1['Approval'] = ['No','No','No','No','Yes']
Drug1

Company name  Country Clinical Trials Side effects  Price in $ Approval
0        Biocon    India         Phase-I     Moderate         100       No
1         Merck  Germany        Phase-II         None         200       No
2          BIPI      USA       Phase-III       Lethal         240       No
3  Novo Nordisc  Denmark        Phase-II         None         100       No
4           BMS      USA        Phase-II         None         250      Yes

In [ ]:
New_list= Drug1.drop(1,axis=0).copy() # COPY FUNCTION WILL NOT CHANGE THE MAIN DATA
print(New_list)
Drug1

   Company name  Country Clinical Trials Side effects  Price in $ Approval
0        Biocon    India         Phase-I     Moderate         100       No
2          BIPI      USA       Phase-III       Lethal         240       No
3  Novo Nordisc  Denmark        Phase-II         None         100       No
4           BMS      USA        Phase-II         None         250      Yes


Company name  Country Clinical Trials Side effects  Price in $ Approval
0        Biocon    India         Phase-I     Moderate         100       No
1         Merck  Germany        Phase-II         None         200       No
2          BIPI      USA       Phase-III       Lethal         240       No
3  Novo Nordisc  Denmark        Phase-II         None         100       No
4           BMS      USA        Phase-II         None         250      Yes

In [ ]:
Drug1.drop(1,axis=0,inplace= True)#  inplace will change the main data
Drug1

Company name  Country Clinical Trials Side effects  Price in $ Approval
0        Biocon    India         Phase-I     Moderate         100       No
2          BIPI      USA       Phase-III       Lethal         240       No
3  Novo Nordisc  Denmark        Phase-II         None         100       No
4           BMS      USA        Phase-II         None         250      Yes

In [ ]:
New_list.reset_index()# IMP function- if any row is deleted and you want to bring it back

index  Company name  Country Clinical Trials Side effects  Price in $  \
0      0        Biocon    India         Phase-I     Moderate         100   
1      2          BIPI      USA       Phase-III       Lethal         240   
2      3  Novo Nordisc  Denmark        Phase-II         None         100   
3      4           BMS      USA        Phase-II         None         250   

  Approval  
0       No  
1       No  
2       No  
3      Yes

In [ ]:
New_list.reset_index(drop=True,inplace=True)# IMP function- if any row is deleted and you want to bring it back
New_list

Company name  Country Clinical Trials Side effects  Price in $ Approval
0        Biocon    India         Phase-I     Moderate         100       No
1          BIPI      USA       Phase-III       Lethal         240       No
2  Novo Nordisc  Denmark        Phase-II         None         100       No
3           BMS      USA        Phase-II         None         250      Yes

##2.5) Pandas combining DataFrame by Concat,Join and Merge

In [ ]:
# practice
import pandas as pd
data_cust= pd.DataFrame({'CustomerID':[101,102,103,103],
                         'Category':['medium','medium','high','low'],
                         'first visit':['yes','no','yes','yes'],
                         'sales':[123,52,214,663],
                         'index':[0,1,2,3]})
data_cust

CustomerID Category first visit  sales  index
0         101   medium         yes    123      0
1         102   medium          no     52      1
2         103     high         yes    214      2
3         103      low         yes    663      3

In [ ]:
# to calculate measures of central tendency (mean,mode,median,standard deviation) in sales column
data_cust['sales'].mean()
print('mean:',data_cust['sales'].mean())
data_cust['sales'].median()
print('median:', data_cust['sales'].median())
data_cust['sales'].mode()
print('mode:',data_cust['sales'].mode())
data_cust['sales'].std()
print('standard deviation:', data_cust['sales'].std())
data_cust['sales'].sum()
print('sum:', data_cust['sales'].sum)

mean: 263.0
median: 168.5
mode: 0     52
1    123
2    214
3    663
Name: sales, dtype: int64
standard deviation: 274.7859773229583
sum: <bound method Series.sum of 0    123
1     52
2    214
3    663
Name: sales, dtype: int64>


In [ ]:
data_cust['Location'] = ['Chicago','London','Boston','Tokyo']
data_cust

CustomerID Category first visit  sales  index Location
0         101   medium         yes    123      0  Chicago
1         102   medium          no     52      1   London
2         103     high         yes    214      2   Boston
3         103      low         yes    663      3    Tokyo

In [ ]:
data_cust.reset_index(drop=True,inplace=True)
data_cust

CustomerID Category first visit  sales  index Location
0         101   medium         yes    123      0  Chicago
1         102   medium          no     52      1   London
2         103     high         yes    214      2   Boston
3         103      low         yes    663      3    Tokyo

In [ ]:
data_cust.sort_values('sales',ascending= True)

CustomerID Category first visit  sales  index Location
1         102   medium          no     52      1   London
0         101   medium         yes    123      0  Chicago
2         103     high         yes    214      2   Boston
3         103      low         yes    663      3    Tokyo

In [ ]:
data_cust= pd.DataFrame({'CustomerID':['101','102','103','104'],
                         'Category':['medium','medium','high','low'],
                         'first visit':['yes','no','yes','yes'],
                         'sales':[123,52,214,663]},
                         index=[0,1,2,3])
data_cust_new = pd.DataFrame({'CustomerID': ['101','103','104','105'],
                              'distance':[12,9,44,21],
                              'sales':[123,214,663,331]},
                             index=[4,5,6,7])

In [ ]:
data_cust

CustomerID Category first visit  sales
0        101   medium         yes    123
1        102   medium          no     52
2        103     high         yes    214
3        104      low         yes    663

In [ ]:
data_cust_new

CustomerID  distance  sales
4        101        12    123
5        103         9    214
6        104        44    663
7        105        21    331

In [ ]:
# 1.concat
pd.concat([data_cust,data_cust_new])

CustomerID Category first visit  sales  distance
0        101   medium         yes    123       NaN
1        102   medium          no     52       NaN
2        103     high         yes    214       NaN
3        104      low         yes    663       NaN
4        101      NaN         NaN    123      12.0
5        103      NaN         NaN    214       9.0
6        104      NaN         NaN    663      44.0
7        105      NaN         NaN    331      21.0

In [ ]:
pd.concat([data_cust,data_cust_new], axis=0)

CustomerID Category first visit  sales  distance
0        101   medium         yes    123       NaN
1        102   medium          no     52       NaN
2        103     high         yes    214       NaN
3        104      low         yes    663       NaN
4        101      NaN         NaN    123      12.0
5        103      NaN         NaN    214       9.0
6        104      NaN         NaN    663      44.0
7        105      NaN         NaN    331      21.0

In [ ]:
pd.concat([data_cust,data_cust_new],axis=1)

CustomerID Category first visit  sales CustomerID  distance  sales
0        101   medium         yes  123.0        NaN       NaN    NaN
1        102   medium          no   52.0        NaN       NaN    NaN
2        103     high         yes  214.0        NaN       NaN    NaN
3        104      low         yes  663.0        NaN       NaN    NaN
4        NaN      NaN         NaN    NaN        101      12.0  123.0
5        NaN      NaN         NaN    NaN        103       9.0  214.0
6        NaN      NaN         NaN    NaN        104      44.0  663.0
7        NaN      NaN         NaN    NaN        105      21.0  331.0

In [ ]:
#2. Merge- Merge can be done by union (outer) and intersection (inner), merge is based on column
pd.merge(data_cust,data_cust_new, how = 'outer', on = 'CustomerID') # Outer merge is union of on

CustomerID Category first visit  sales_x  distance  sales_y
0        101   medium         yes    123.0      12.0    123.0
1        102   medium          no     52.0       NaN      NaN
2        103     high         yes    214.0       9.0    214.0
3        104      low         yes    663.0      44.0    663.0
4        105      NaN         NaN      NaN      21.0    331.0

In [ ]:
#2. Merge- Merge can be done by union (outer) and intersection (inner)
pd.merge(data_cust,data_cust_new, how = 'inner', on = 'CustomerID') # Inner merge is intersection of on

CustomerID Category first visit  sales_x  distance  sales_y
0        101   medium         yes      123        12      123
1        103     high         yes      214         9      214
2        104      low         yes      663        44      663

In [ ]:
# merge on the basis of precceding (left) or suceeding (right) data frame
pd.merge(data_cust,data_cust_new,how = 'left',on='CustomerID')

CustomerID Category first visit  sales_x  distance  sales_y
0        101   medium         yes      123      12.0    123.0
1        102   medium          no       52       NaN      NaN
2        103     high         yes      214       9.0    214.0
3        104      low         yes      663      44.0    663.0

In [ ]:
# merge on the basis of precceding (left) or suceeding (right) data frame
pd.merge(data_cust,data_cust_new,how = 'right',on='CustomerID')

CustomerID Category first visit  sales_x  distance  sales_y
0        101   medium         yes    123.0        12      123
1        103     high         yes    214.0         9      214
2        104      low         yes    663.0        44      663
3        105      NaN         NaN      NaN        21      331

In [ ]:
# Join- it will join two datafarme on the basis of index value
df1=pd.DataFrame({'Q1':[100,200,300],'Q2':[200,200,100]},index= [0,1,2])
df2=pd.DataFrame({'Q3':[100,200,300],'Q4':[101,201,301]},index= [0,2,3])

In [ ]:
df1

Q1   Q2
0  100  200
1  200  200
2  300  100

In [ ]:
df2

Q3   Q4
0  100  101
2  200  201
3  300  301

In [ ]:
df2.join(df1, how ='right'), #outer,inner,left and right works same as merge

(      Q3     Q4   Q1   Q2
 0  100.0  101.0  100  200
 1    NaN    NaN  200  200
 2  200.0  201.0  300  100,)

##2.6) Saving and Loading Data Sets- In real world we deal with lots of data, so its practically challenging to create datasets. In Python we can upload data and work on them. Like loading excel or google spreadsheets, csv (comma-separated values) files etc.

In [1]:
#to import csv
# to import csv file in google colab from google drive
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
import pandas as pd
path = '/content/StockData 1.csv'
df1 = pd.read_csv(path)
df1.head() # to see top 5 rows in data set

stock        date    price
0  AAPL    8/2/2013  67.8542
1  AAPL   11/2/2013  68.5614
2  AAPL   12/2/2013  66.8428
3  AAPL  13-02-2013  66.7156
4  AAPL  14-02-2013  66.6556

In [6]:
df1.sort_values('price', ascending = True) # sort based on conditions

stock        date   price
4072   ZTS   11/4/2014   28.40
4073   ZTS  14-04-2014   28.48
4075   ZTS  16-04-2014   28.53
4074   ZTS  15-04-2014   28.55
4076   ZTS  17-04-2014   28.60
...    ...         ...     ...
1247  AAPL  23-01-2018  177.04
1241  AAPL   12/1/2018  177.09
1245  AAPL  19-01-2018  178.46
1243  AAPL  17-01-2018  179.10
1244  AAPL  18-01-2018  179.26

[5036 rows x 3 columns]

In [7]:
# to calculate measures of central tendency
df1['price'].mean() #  to calculate the average
print('mean:',df1['price'].mean())

mean: 73.05702966640192


In [8]:
df1['price'].median()

69.08500000000001

In [9]:
df1['price'].mode() # most commonly occuring value

0    74.59
Name: price, dtype: float64

In [10]:
df1['price'].mode()[0] # to access the first mode, if there are more than one mode, so to access the first mode

74.59

In [11]:
df1['stock'].mode() # to check the mode value of column

0    AAPL
1     SNI
2     TJX
3     ZTS
Name: stock, dtype: object

In [12]:
df1['price'].std()

29.011126440938973

In [13]:
df1['price'].sum()

367915.2014

In [5]:
path = '/content/StockData 2.xlsx' # if the file is excel file
df_excel = pd.read_excel(path)
df_excel

stock       date    price
0     AAPL 2013-02-08  67.8542
1     AAPL 2013-02-11  68.5614
2     AAPL 2013-02-12  66.8428
3     AAPL 2013-02-13  66.7156
4     AAPL 2013-02-14  66.6556
...    ...        ...      ...
5031   ZTS 2018-02-01  77.8200
5032   ZTS 2018-02-02  76.7800
5033   ZTS 2018-02-05  73.8300
5034   ZTS 2018-02-06  73.2700
5035   ZTS 2018-02-07  73.8600

[5036 rows x 3 columns]

In [14]:
# to save csv file in google drive
df1.to_csv('/content/drive/MyDrive/df1.csv',index= False)

In [15]:
# to save excel file in google drive
df_excel.to_excel('/content/StockData 2.xlsx', index= False)

In [16]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


##2.7) Pandas - Functions

In [18]:
df1.head() # to see 5 rows from top

stock        date    price
0  AAPL    8/2/2013  67.8542
1  AAPL   11/2/2013  68.5614
2  AAPL   12/2/2013  66.8428
3  AAPL  13-02-2013  66.7156
4  AAPL  14-02-2013  66.6556

In [19]:
df1.tail(5) # to see 5 rows from bottom

stock      date  price
5031   ZTS  1/2/2018  77.82
5032   ZTS  2/2/2018  76.78
5033   ZTS  5/2/2018  73.83
5034   ZTS  6/2/2018  73.27
5035   ZTS  7/2/2018  73.86

In [20]:
df1.shape # to see number of rows and columns

(5036, 3)

In [21]:
df1['price'].min() # to see minimum value in a column

28.4

In [22]:
df1['price'].max() # to see the maximum value in a column

179.26

In [23]:
df1.info() # to see the information about the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5036 entries, 0 to 5035
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   stock   5036 non-null   object 
 1   date    5036 non-null   object 
 2   price   5036 non-null   float64
dtypes: float64(1), object(2)
memory usage: 118.2+ KB


In [24]:
df1['stock'].unique() # to see the unique values in a column, this will make output as array

array(['AAPL', 'SNI', 'TJX', 'ZTS'], dtype=object)

In [25]:
df1['stock'].value_counts() # to see the count of values in a column

stock
AAPL    1259
SNI     1259
TJX     1259
ZTS     1259
Name: count, dtype: int64

In [26]:
df1['stock'].value_counts(normalize = True) # this divides values to the total count, this tells us the relative frequency of the value, eg in AAPL 1259/5036

stock
AAPL    0.25
SNI     0.25
TJX     0.25
ZTS     0.25
Name: proportion, dtype: float64

In [27]:
# to group values in the categories we use .groupby(['  '])
df1.groupby('stock')['price'].mean() # to group values based on category like stock and calculate mean

stock
AAPL    109.066698
SNI      71.319206
TJX      66.743566
ZTS      45.098648
Name: price, dtype: float64

In [28]:
df1.groupby('stock')['price'].median() # to group values based on category like stock and calculate median

stock
AAPL    109.01
SNI      72.31
TJX      68.85
ZTS      45.62
Name: price, dtype: float64

In [29]:
# if we want to create our own function we use apply function, first we have to define the function using def command and then use apply function to apply it.
# create a function that increases the price of stock by 10%
def profit(price):
  return price+price*0.10

In [30]:
df1['price'].apply(profit)

0       74.63962
1       75.41754
2       73.52708
3       73.38716
4       73.32116
          ...   
5031    85.60200
5032    84.45800
5033    81.21300
5034    80.59700
5035    81.24600
Name: price, Length: 5036, dtype: float64

In [31]:
# if we want to save this value as a new column (new_price) in main data
df1['new_price']= df1['price'].apply(profit)
df1

stock        date    price  new_price
0     AAPL    8/2/2013  67.8542   74.63962
1     AAPL   11/2/2013  68.5614   75.41754
2     AAPL   12/2/2013  66.8428   73.52708
3     AAPL  13-02-2013  66.7156   73.38716
4     AAPL  14-02-2013  66.6556   73.32116
...    ...         ...      ...        ...
5031   ZTS    1/2/2018  77.8200   85.60200
5032   ZTS    2/2/2018  76.7800   84.45800
5033   ZTS    5/2/2018  73.8300   81.21300
5034   ZTS    6/2/2018  73.2700   80.59700
5035   ZTS    7/2/2018  73.8600   81.24600

[5036 rows x 4 columns]

In [32]:
df1.head(5)

stock        date    price  new_price
0  AAPL    8/2/2013  67.8542   74.63962
1  AAPL   11/2/2013  68.5614   75.41754
2  AAPL   12/2/2013  66.8428   73.52708
3  AAPL  13-02-2013  66.7156   73.38716
4  AAPL  14-02-2013  66.6556   73.32116

In [33]:
df1['new_price'].head(5)

0    74.63962
1    75.41754
2    73.52708
3    73.38716
4    73.32116
Name: new_price, dtype: float64

In [34]:
df1.sort_values('new_price', ascending = False) # to sort values on descending order, for descending order we have to write False in ascending as descending function doesn't exist

stock        date   price  new_price
1244  AAPL  18-01-2018  179.26    197.186
1243  AAPL  17-01-2018  179.10    197.010
1245  AAPL  19-01-2018  178.46    196.306
1241  AAPL   12/1/2018  177.09    194.799
1247  AAPL  23-01-2018  177.04    194.744
...    ...         ...     ...        ...
4076   ZTS  17-04-2014   28.60     31.460
4074   ZTS  15-04-2014   28.55     31.405
4075   ZTS  16-04-2014   28.53     31.383
4073   ZTS  14-04-2014   28.48     31.328
4072   ZTS   11/4/2014   28.40     31.240

[5036 rows x 4 columns]

In [35]:
import datetime
date = datetime.date(2022, 1, 29)
print(date)

2022-01-29


In [36]:
import numpy as np
import pandas as pd
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))
demo_matrix

array([[13, 35, 74, 48],
       [23, 37, 37, 38],
       [73, 39, 93, 39]])

In [37]:
demo_matrix[0:3, 1:3]

array([[35, 74],
       [37, 37],
       [39, 93]])

In [38]:
flowers = pd.Series([2, 3, 5, 4], index=['lily', 'rose', 'daisy', 'lotus'])
flowers['daisy']

5

In [39]:
# date and time function
df_excel

stock       date    price
0     AAPL 2013-02-08  67.8542
1     AAPL 2013-02-11  68.5614
2     AAPL 2013-02-12  66.8428
3     AAPL 2013-02-13  66.7156
4     AAPL 2013-02-14  66.6556
...    ...        ...      ...
5031   ZTS 2018-02-01  77.8200
5032   ZTS 2018-02-02  76.7800
5033   ZTS 2018-02-05  73.8300
5034   ZTS 2018-02-06  73.2700
5035   ZTS 2018-02-07  73.8600

[5036 rows x 3 columns]

In [40]:
df_excel.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5036 entries, 0 to 5035
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   stock   5036 non-null   object        
 1   date    5036 non-null   datetime64[ns]
 2   price   5036 non-null   float64       
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 118.2+ KB


In [41]:
# to convert string/object to date time format
df_excel['date'] = pd.to_datetime(df_excel['date'],dayfirst=True) # we use dayfirst = True if the date format is Date/Month/Year. If date is not in this format than we can ignose datefirst=True function.

In [42]:
df_excel.info() # here [ns] means number of seconds.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5036 entries, 0 to 5035
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype         
---  ------  --------------  -----         
 0   stock   5036 non-null   object        
 1   date    5036 non-null   datetime64[ns]
 2   price   5036 non-null   float64       
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 118.2+ KB


In [43]:
df_excel # the format of date has changed to year-month-date, pandas has different date-time formats we can google it further.

stock       date    price
0     AAPL 2013-02-08  67.8542
1     AAPL 2013-02-11  68.5614
2     AAPL 2013-02-12  66.8428
3     AAPL 2013-02-13  66.7156
4     AAPL 2013-02-14  66.6556
...    ...        ...      ...
5031   ZTS 2018-02-01  77.8200
5032   ZTS 2018-02-02  76.7800
5033   ZTS 2018-02-05  73.8300
5034   ZTS 2018-02-06  73.2700
5035   ZTS 2018-02-07  73.8600

[5036 rows x 3 columns]

In [44]:
# we can change the format of date
df_excel['date'].dt.strftime('%m-%d-%Y') # capital 'Y' gives value of the year in four digits, strf means string format time

0       02-08-2013
1       02-11-2013
2       02-12-2013
3       02-13-2013
4       02-14-2013
           ...    
5031    02-01-2018
5032    02-02-2018
5033    02-05-2018
5034    02-06-2018
5035    02-07-2018
Name: date, Length: 5036, dtype: object

In [45]:
df_excel['date'].dt.strftime('%m/%d/%y') # small 'y' gives value of the year in two digits

0       02/08/13
1       02/11/13
2       02/12/13
3       02/13/13
4       02/14/13
          ...   
5031    02/01/18
5032    02/02/18
5033    02/05/18
5034    02/06/18
5035    02/07/18
Name: date, Length: 5036, dtype: object

In [46]:
# extracting year
df_excel['date'].dt.year

0       2013
1       2013
2       2013
3       2013
4       2013
        ... 
5031    2018
5032    2018
5033    2018
5034    2018
5035    2018
Name: date, Length: 5036, dtype: int32

In [47]:
# creating a new column called 'Year' containing year values
df_excel['Year']= df_excel['date'].dt.year
df_excel

stock       date    price  Year
0     AAPL 2013-02-08  67.8542  2013
1     AAPL 2013-02-11  68.5614  2013
2     AAPL 2013-02-12  66.8428  2013
3     AAPL 2013-02-13  66.7156  2013
4     AAPL 2013-02-14  66.6556  2013
...    ...        ...      ...   ...
5031   ZTS 2018-02-01  77.8200  2018
5032   ZTS 2018-02-02  76.7800  2018
5033   ZTS 2018-02-05  73.8300  2018
5034   ZTS 2018-02-06  73.2700  2018
5035   ZTS 2018-02-07  73.8600  2018

[5036 rows x 4 columns]

In [48]:
# creating a new column called 'Month' containing month values
df_excel['Month']= df_excel['date'].dt.month
df_excel

stock       date    price  Year  Month
0     AAPL 2013-02-08  67.8542  2013      2
1     AAPL 2013-02-11  68.5614  2013      2
2     AAPL 2013-02-12  66.8428  2013      2
3     AAPL 2013-02-13  66.7156  2013      2
4     AAPL 2013-02-14  66.6556  2013      2
...    ...        ...      ...   ...    ...
5031   ZTS 2018-02-01  77.8200  2018      2
5032   ZTS 2018-02-02  76.7800  2018      2
5033   ZTS 2018-02-05  73.8300  2018      2
5034   ZTS 2018-02-06  73.2700  2018      2
5035   ZTS 2018-02-07  73.8600  2018      2

[5036 rows x 5 columns]